language: ruby
cache:
  bundler: true
  directories:
    - bower_components
sudo: false
rvm:
  - 2.0.0
before_script:
  - npm install bower
  - bundle exec rake compile
  - bundle exec rake serve > /dev/null 2>&1 &
  - export PID=$!
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start
script:
  - bundle exec rake spec
after_failure:
  - bundle exec rake upload
after_script:
  - kill -2 $PID
  - sleep 2
